name: Costello
colors:
  - Green
  - Blue
  - Magenta
  - Yellow
seo:
  description: 'The sales intelligence platform that guides your reps to ask the right questions, provides them with real-time suggestions, and forms the habits that close more deals.'
baseurl:
url: 'https://andcostello.com'
address:
  street: 525 Union St.
  suite: Suite 1A2
  city: Indianapolis
  state: IN
  zip: 46225
phone: 317.520.4325
social:
  github: https://github.com/andcostello
  email: contact@andcostello.com
  facebook: https://www.facebook.com/You.andCostello/
  twitter: https://twitter.com/andCostello
  linkedin: https://www.linkedin.com/company-beta/16234555/
author:
  name: Costello
  email: contact@andcostello.com
  github: contact@andcostello.com
  facebook: andcostello
  twitter: andcostello
  show_on_post: true
permalink: '/:categories/:title/'
sass:
  style: compressed
paginate: 5
paginate_path: '/:num/'
markdown: kramdown
datanyze:
  tracking_id: m4VVPteoiYA%3D
google:
  tag_manager:
    container_id: GTM-N537LXB
  adwords:
    conversion_id: 851313951
    conversion_language: "en"
    conversion_format: 3
    conversion_color: ffffff
    conversion_label: gWKiCOGn-XEQn4r4lQM
    remarketing_only: false
linkedin:
  partner_id: 51982
facebook:
  pixel_id: 1402733833127292
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - Rakefile
