title: Costello

incremental: true

# permalink: pretty

port: 8080

collections:
  posts:
    permalink: /blog/:categories/:title/
  team:
    output: true
    permalink: /:collection/:name
  videos:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope: 
      path: "" 
      type: "team"
    values:
      layout: "team-member"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
  -
    scope:
      path: ""
      type: "videos"
    values:
      layout: "videos"    