title: Costello

collections: 
  team:
    output: true

defaults:
  -
    scope: 
      path: "" 
      type: "team"
    values:
      layout: "team-member"
      _defaults:
        job_title: "insert job title here"