title: Costello

incremental: true

port: 8080

collections:
  posts:
    permalink: /:categories/:title/
  team:
    output: true
  api:
    output: true

defaults:
  -
    scope: 
      path: "" 
      type: "team"
    values:
      layout: "team-member"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"