title: Costello
description: Setup every sales rep to perform like your best rep.

facebook: https://www.facebook.com/andcostello
twitter: https://www.twitter.com/@andcostello

default_image: https://unsplash.it/700/466

# incremental: true

# permalink: pretty

port: 8080

collections:
  posts:
    permalink: /resources/blog/:categories/:title/
  team:
    output: true
    permalink: /:collection/:name
  videos:
    output: true
    permalink: /resources/:collection/:name
  press:
    output: true
    permalink: /resources/:collection/:name  

defaults:
  -
    scope: 
      path: "" 
      type: "team"
    values:
      layout: "team-member"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
      author: "Kirsten Bell"
  -
    scope:
      path: ""
      type: "videos"
    values:
      layout: "videos"
  -
    scope:
      path: ""
      type: "press"
    values:
      layout: "press"
      internal: true